### ISSUE TITLE
Cannot assign source in bulk to products

### ISSUE THREAD

**Issue by phizab** [magento/inventory#2154] opened 2019-04-09 10:57 UTC
### Preconditions (*)

1. Magento 2.3.1
2. Configuration "cataloginventory/bulk_operations/async" is enabled

### Steps to reproduce (*)

1. Select product(s) in product grid.
2. Choose "Assign Inventory Source"
3. Set checkbox of any source
4. Click "Assign sources"

### Expected result (*)

1. Bulk is getting scheduled

### Actual result (*)

1. Redirect to product grid
2. Error Message: "Something went wrong during the operation."
3. Error in log: "Topic "async.V1.inventory.bulk-product-source-assign.POST" is not configured. {"exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): Topic \"async.V1.inventory.bulk-product-source-assign.POST\" is not configured. at /var/www/html/vendor/magento/framework/Communication/Config.php:39)"}"
4. Bulk is created, but not scheduled

When I debugged the code I saw that the topic name "async.V1.inventory.bulk-product-source-assign.POST" is used in [BulkAssignPost](https://github.com/magento-engcom/msi/blob/13d2740253463dabd5664dbe5f1248a563892ec0/app/code/Magento/InventoryCatalogAdminUi/Controller/Adminhtml/Source/BulkAssignPost.php#L122), but in \Magento\Framework\Communication\Config the topic is named "async.magento.inventorycatalogapi.api.bulksourceassigninterface.execute.post". Am I doing anything wrong or what is the problem here? Sorry, I'm new to message queues.

Same for BulkUnassignPost and BulkTransferPost.

**Comment by maghamed** [comment] 2019-04-09 12:20
Hi @phizab ,

This issue is addressed in this PR - https://github.com/magento-engcom/msi/pull/2086
which is, unfortunately, not yet released. 
The root cause of the issue is topic names change which happened since 2.3.1 release.

While this PR is not delivered to any MSI release - you can still use synchronous transfer which is quite fast at this moment, as it was refactored recently and now it moves the whole bunch of SourceItems at a time, but not proceed item by item as it was before.

**Comment by maghamed** [comment] 2019-04-10 10:12
@phizab 
I will close this issue, as it was already addressed in the scope of delivered PR.

Feel free to re-open if you consider that existing fix does not apply for you.

**Closed as completed by maghamed** 2019-04-10 10:12 UTC
