### ISSUE TITLE
Sales Supports MSI

### ISSUE THREAD

**Issue by vrann** [magento/inventory#602] opened 2018-02-23 18:43 UTC
AC:
- orders in different statuses placed correctly with different configuration options

**Comment by mbrinton01** [comment] 2018-03-07 18:27
List here: https://github.com/magento-engcom/msi/wiki/Inventory-Options-List

**Comment by mbrinton01** [comment] 2018-03-07 18:28
Duplicate of #611

**Closed as completed by mbrinton01** 2018-03-07 18:28 UTC
Labels: Epic
