### ISSUE TITLE
Configurable Product Presents on Category Page When All It's Children Set to "Out of Stock"

### ISSUE THREAD

**Issue by nmalevanec** [magento/inventory#1029] opened 2018-04-26 08:38 UTC
### Preconditions
1. Magento with enabled MSI

### Steps to reproduce
1. Login to admin area.
2. Navigate to Store > Manage Sources.
3. Add new source "Test Source"(code: "test_source").
4. Navigate to Store > Manage Stocks.
5. Add new stock "Test Stock". Do not assign it current website.
6. Assign "Test Source" to "Test Stock".
7. Perform reindex and flush cache.
8. Navigate to Catalog > Products.
9. Start creating configurable product.
10. Fill necessary data:
Product Name: "configurable product"
SKU: configurable product
Price: 3
11. Assign it to some category.
12. Start creating configurations.
13. At "Select Attributes" step select color attribute.
14. At "Attribute Value" step create two options: "blue" and "red".
15. At "Bulk Images & Price" step check "Apply single quantity to each SKUs" and assign "default" source with qty = 100 (NOTE: do not assign options to "Test Source").
16. Generate products.
17. Set some weight for generated products.
18. Save configurable.
19. Navigate to storefront, configurable category view page .
20. Check configurable is present on category view page..
21. Login to admin area.
22. Set both configurable options to "Out of Stock" on default source.
23. Navigate to storefront category view page.

### Expected result
1. Configurable product is absent on category view page.

### Actual result
1.  Configurable product has "Out of Stock" status, but still presents on category view page.

**Comment by RomaKis** [comment] 2018-04-26 11:42
Close as duplicate of https://github.com/magento-engcom/msi/issues/904.

**Comment by nmalevanec** [comment] 2018-05-04 08:01
@RomaKis, please re-check this issue on latest 2.3-develop and branch MSI-856-extend-salability-interface. Looks like it's reproducible on both.

**Comment by naydav** [comment] 2018-05-16 09:17
https://github.com/magento-engcom/msi/pull/1153

**Closed as completed by naydav** 2018-05-16 09:17 UTC
Labels: Bug
