### ISSUE TITLE
404 error page not found for the creating the new configurable product.

### ISSUE THREAD

**Issue by Datta** [magento/inventory#2789] opened 2020-01-24 13:36 UTC
Preconditions (*)
Magento version 2.3.2
Steps to reproduce (*)
create new configurable product
enter required field values
create configurations
select any attribute (in my case size),select attribute values
Apply unique quantity by attribute to each SKU
select sources
generate products then Hit "Save" to save your changes.
Expected result (*)
product should be saved
page reload the newly created configurable product
Actual result (*)
Page makes a POST request with all the data to
http://abc.com.au/admin/catalog/product/validate/type/configurable/store/0/set/14/key/bf71c17ac808e40388dbaab5f237110b9937e4a849fc77812f1349d028a60acb/?isAjax=true
but it seems that request gets a blank/empty response. 404 error: Page not found ?
http://abc.com.au/admin/catalog/product/save/type/configurable/store/0/set/14/key/8af044777c7e40375c80b27c31a597eb7a26e99a2a322cefd45ec4ee80895566/back/edit
2020-01-08_1837

![image](https://user-images.githubusercontent.com/356098/73073095-9a428780-3edc-11ea-9b08-074acbea6de1.png)

**Comment by Datta** [comment] 2020-01-24 13:38
I got this issue on the Multi Website and multi store. 
To Reproduce the issue please follow the below steps. 
steps:
Step 1: Select Attributes
At the bottom of Product Details, expand the Configurations section. Then, tap Create Configurations.

Configurations

Mark the checkbox of each attribute that is to be used as a configuration.
If you need to add a new attribute, tap Create New Attribute. Complete the attribute properties, and tap Save Attribute. Then, mark the checkbox to select the attribute.
In the upper-right corner, tap Next.

Select Attributes

Step 2: Enter Attribute Values
Mark the checkbox of each variation of the product.
To add a new value, click Create New Value. Then, enter the new value in the input box, and tap the Enter arrow.
Repeat these steps for each attribute that is included as a configuration.

You can rearrange the list of attributes by dragging the box in the upper-left corner to a new position.

In the upper-right corner, tap Next.

Step 3:
Apply Different Quantity by Attribute

If the quantity is the different for each SKU, select Apply unique quantity by attribute to each SKU.
Enter the Quantity for each.
Different Quantities per Attribute

When complete, tap Next in the upper-right corner.

Step 4: Generate the Product Configurations
Wait a moment for the list of products to appear. When you are ready to add the products to your catalog, tap Generate Products.

The product variations now appear at the bottom of Product Details in the Configuration section.

If you want to edit any of the settings, tap Edit Configurations.

Generate Products

Step 5: Publish the Products
If you are ready to publish the products in the catalog, set the Product Online switch to the “On” position. Otherwise, leave the switch in the “Off” position until the product is ready to publish.
When complete, on the Save menu and it gives the error 404 page not found to save the product.

**Comment by smoskaluk** [comment] 2020-01-29 08:53
Hi @Datta , I couldn't reproduce your issue. May you please describe settings of sources - stocks - sales channels (websites) and other details of your configuration. When you create configuration for product - which sources you select for your options?  Do you use any 3d part extensions in your instance?

**Comment by sidolov** [comment] 2020-02-04 17:12
Hi @Datta I'm closing this issue since we haven't enough information to reproduce it. 
Feel free to add additional steps and reopen it!
Thank you for your collaboration!

**Closed as completed by sidolov** 2020-02-04 17:12 UTC
Labels: needs update
