### ISSUE TITLE
When you click on "Reset" in the 'Columns' drop down menu it disables ALL columns on the Product grid page.

### ISSUE THREAD

**Issue by ivy00johns** [magento/inventory#1640] opened 2018-09-13 16:12 UTC
### Preconditions
1. Magento MSI

### Steps to reproduce
1. Navigate to "CATALOG" > Products.
2. Click on "Columns".
3. Click on "Reset".

### Expected Result
1. The default Columns should be checked like other Grid pages when you click on "Reset".

### Actual Result
![image.png](https://images.zenhubusercontent.com/5a679b134b5806bc2bc400ab/1249fe31-6a51-4a25-8325-899bc1a08150)
![image.png](https://images.zenhubusercontent.com/5a679b134b5806bc2bc400ab/bc6e9d86-121e-4fab-b8eb-0de8edc2d3af)

**Comment by phoenix128** [comment] 2018-09-24 14:02
Just tried with latest version and it seems to be working.

<img src="https://i.imgur.com/znC2FEV.gif" />

Should we close this issue?

**Comment by maghamed** [comment] 2018-09-26 14:45
@ivy00johns  could you please re-check that once again on a fresh Magento + MSI installation, and if the issue is not reproducible close one

**Closed as completed** 2019-03-15 21:07 UTC
