### ISSUE TITLE
Can't set stock for diferents scopes

### ISSUE THREAD

**Issue by agallart** [magento/inventory#3059] opened 2020-03-26 10:08 UTC
### Preconditions (*)

1. Magento 2.3.3
2. enable Inventory Management

### Steps to reproduce (*)

1.create Websites

![image](https://user-images.githubusercontent.com/16067982/77633171-5eb15180-6f4f-11ea-8691-543a612e4e23.png)

2.create Source
![image](https://user-images.githubusercontent.com/16067982/77633063-2f9ae000-6f4f-11ea-951d-cc613a2d75f1.png)

3.create Stocks
![image](https://user-images.githubusercontent.com/16067982/77633139-4e997200-6f4f-11ea-9971-65bc13378022.png)

4.create product

![image](https://user-images.githubusercontent.com/16067982/77633266-80aad400-6f4f-11ea-93f8-b1e1fe7c6f81.png)

add qty into source

![image](https://user-images.githubusercontent.com/16067982/77633336-991aee80-6f4f-11ea-8f2d-bd39bb699346.png)

### Actual result (*)

I expect diferents qty for diferents scopes but return same result 
![image](https://user-images.githubusercontent.com/16067982/77634253-f499ac00-6f50-11ea-8741-e424aa675f80.png)

![image](https://user-images.githubusercontent.com/16067982/77634332-109d4d80-6f51-11ea-9b21-cad87883a80f.png)

i try to change stock_id with error

![image](https://user-images.githubusercontent.com/16067982/77634415-3296d000-6f51-11ea-8331-f1741be7752a.png)

### Expected result (*)

1. Diferent stock for diferents scopes

**Comment by TadeuRodrigues** [comment] 2020-05-28 19:44
hi, you can use 'rest/V1/inventory/get-product-salable-quantity/prova/2'

**Comment by smoskaluk** [comment] 2020-06-04 14:47
Hi @agallart! Please recheck MSI documentation to see that by design website as sales channel can be assigned to one stock only and stock items could not be different in different scopes

**Closed as completed by smoskaluk** 2020-06-04 14:47 UTC
