### ISSUE TITLE
Switch Off CatalogInventory Indexation and substitute one with MSI

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#490] opened 2018-02-01 14:05 UTC
Switch Off CatalogInventory Indexation and substitute one with MSI.

MSI brings new Inventory indexation for Inventory as well as synchronization between new and legacy CatalogInventory data storage. Thus, MSI could be considered as a source of truth for inventory data. Taking that into account we can disable in a backward compatible fashion existing Cataloginventory index and substitute one with MSI indexation

**Comment by naydav** [comment] 2018-02-06 21:27
Looks like it is duplicate of 
https://github.com/magento-engcom/msi/issues/220

**Closed as completed** 2018-02-13 16:29 UTC
