### ISSUE TITLE
M2 Out-Of-Stock Threshold Not-Working

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#2745] opened 2019-12-04 03:50 UTC
I'm running:

Out-Of-Stock Threshold: -1000
Qty: 1
Stock Status: In Stock
Salable Qty: 1001
Update Stock to 0 Push to M2

Out-Of-Stock Threshold: -1000
Qty: 0
Stock Status: Out Of Stock
Salable Qty: 0

https://www.reddit.com/r/Magento/comments/dvw7oy/m2_outofstock_threshold_notworking/

**Comment by smoskaluk** [comment] 2019-12-04 09:55
Hi @maghamed , I couldn't reproduce this issue on 2.3 develop branch

**Comment by ishakhsuvarov** [comment] 2019-12-04 17:13
@smoskaluk Please share the steps you have tried. Unfortunately, since there is not enough information on the ticket we could try multiple ways: 
* Both product and system level `Out of Stock Threshold` with `use global config` enabled and disabled.
* Set QTY in different ways, given that initial post describes pushing information from the external system we could try different combinations of API calls as well as through the admin ui (to double check)
* Maybe some more combinations. Please note, that both `Salable quantity` and `Stock Status` are incorrect in the actual result, we should closely watch both values change when updating stock.

Please share the scenarios you have executed for testing so that we can think of more ways to diagnose the problem.

Thanks!

**Comment by smoskaluk** [comment] 2019-12-05 10:56
Hi @ishakhsuvarov 
Here my steps how I checked this issue
1. Create custom stock with custom source
2. Create product with qty 1 on default source
3. Create  product with qty 1 on custom source
4. Set backorders 'Allow Qty Below 0' and 'Out-Of-Stock Threshold' = -1000 
(I have tried to set them both ways - as global config and in Advanced Inventory for the products)
5. Salable qty for products = 1001
6. Change qty for the sources = 0
(I did this from admin UI and via REST API calls)
7. Result:  salable qty for products = 1000 , stock status = 'In stock'

![Salable_qty](https://user-images.githubusercontent.com/27818516/70229306-9c9b2780-175e-11ea-8b00-84765b7b539a.png)

**Comment by ishakhsuvarov** [comment] 2019-12-10 15:39
Closing this for now as we could not find an exact scenario where this would be reproducible. Feel free to reopen should the issue occur under clear circumstances.

**Closed as completed by ishakhsuvarov** 2019-12-10 15:39 UTC
Labels: Not Reproduced

**Comment by chadwixk** [comment] 2020-02-10 23:56
> Hi @ishakhsuvarov
> Here my steps how I checked this issue
> 
> 1. Create custom stock with custom source
> 2. Create product with qty 1 on default source
> 3. Create  product with qty 1 on custom source
> 4. Set backorders 'Allow Qty Below 0' and 'Out-Of-Stock Threshold' = -1000
>    (I have tried to set them both ways - as global config and in Advanced Inventory for the products)
> 5. Salable qty for products = 1001
> 6. Change qty for the sources = 0
>    (I did this from admin UI and via REST API calls)
> 7. Result:  salable qty for products = 1000 , stock status = 'In stock'
> 
> ![Salable_qty](https://user-images.githubusercontent.com/27818516/70229306-9c9b2780-175e-11ea-8b00-84765b7b539a.png)

@smoskaluk, which API call did you use, because the [only one I know of](https://devdocs.magento.com/redoc/2.3/admin-rest-api.html#operation/inventoryApiSourceItemsSaveV1ExecutePost) requires you to also pass the Stock Status, which is essentially overriding the Out of Stock Threshold logic that is supposed to determine when to update the Stock Status value?

**Comment by smoskaluk** [comment] 2020-02-11 08:15
@chadwixk Yes, I used POST call /rest/V1/inventory/source-items with such Body 
{
  "sourceItems": [
    {
      "sku": "product SKU",
      "source_code": "Source Code",
      "quantity": 0,
      "status": 1,
      "extension_attributes": {}
    }
  ]
}

**Comment by chadwixk** [comment] 2020-02-11 16:37
@smoskaluk then doesn't the fact that you're passing the stock status override the Out of Stock Threshold functionality?

Essentially, the Out of Stock Threshold functionality determines when to update the Stock Status from In Stock to Out of Stock.

So when you did these steps:

> - 6). Change qty for the sources = 0 (I did this from admin UI and via REST API calls)
> - 7). Result: salable qty for products = 1000 , stock status = 'In stock'

Your REST call in step 6 is what set the Stock Status to In Stock. I don't see how you can test this functionality using the API. The Stock Status Result in Step 7 will always be what you passed in as the Stock Status via that API, not what was determined by the Out of Stock Threshold logic.... unless you are saying that the Out of Stock functionality ignores the stock status you pass in the API and makes its own determination, but that is not what I've found.

If my assumption about that is true, there would need a way to update stock qty via the API WITHOUT passing stock status (making it optional parameter...today it is mandatory). Or by having the stock update logic ignore the stock status passed via the API and determine via the Out of Stock Threshold.
