### ISSUE TITLE
Low stock report for products on custom stock B2B

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#2506] opened 2019-08-21 14:22 UTC
### Preconditions (*)

1. Magento MSI + EE + B2B
2. Custom stock with custom source and Main website
3. Create product assigned to custom source with Qty = 10 and Notify for qty below = 11

### Steps to reproduce (*)

1. Open in admin 'Reports' -> 'Low stock report'

### Expected result (*)

1. Low stock report show your product

### Actual result (*)

1. Product is absent in report

**Comment by ishakhsuvarov** [comment] 2019-09-27 07:17
This issue is only reproducible with EE and B2B.

It looks like module sequence is built differently for EE and InventoryLowStockNotification module can not override layouts from Reports module.

It's possible that fixes would be required in Magento framework to make it work.

**Comment by ishakhsuvarov** [comment] 2019-12-05 17:16
Fixed in https://github.com/magento/inventory/pull/2684

**Closed as completed by ishakhsuvarov** 2019-12-05 17:16 UTC
Labels: Award: special achievement, QA Verified
