### ISSUE TITLE
MSI - Stock used from wrong source (multi store issue)

### ISSUE THREAD

**Issue by digikeijs** [magento/inventory#2108] opened 2019-03-24 19:35 UTC
### Preconditions (*)

1. Magento 2.3
2. MSI version 1.1

### Steps to reproduce (*)

(see screenshots)
1. Setup a multistore setup with 4 websites 
2. Setup 1 extra source
3. Setup 1 extra stock
4. Assign 2 websites to the default stock
5. Assign 2 websites to the extra stock
6.  Assign a product to all websites and both sources and give 0 qty to default stock and 100 to the source.
7. Create an order through the admin for a website linked to the extra source /stock. Add a product with a qty higher then the default stock so higher then 0. You will get the error qty is not available which shows it's using the default stock and not the extra stock

### Expected result (*)

You will get the error qty is not available which shows it's using the default stock and not the extra stock
Stock should always be decucted from the source / stock setup for a specific website.

### Actual result (*)

![MSI1](https://user-images.githubusercontent.com/34745091/55001850-c9931a00-4fd5-11e9-87f4-4449cc8675cf.JPG)
![MSI4](https://user-images.githubusercontent.com/34745091/55001859-cf88fb00-4fd5-11e9-8912-9148d67288d5.JPG)
![MSI2](https://user-images.githubusercontent.com/34745091/55001864-d152be80-4fd5-11e9-8816-049afeb9c0ac.JPG)
![MSI3](https://user-images.githubusercontent.com/34745091/55001869-d31c8200-4fd5-11e9-9f96-32733ca31f8e.JPG)
![MSI5](https://user-images.githubusercontent.com/34745091/55001874-d44daf00-4fd5-11e9-80b3-30a208f07ca2.JPG)
![MSI6](https://user-images.githubusercontent.com/34745091/55001881-d6b00900-4fd5-11e9-88a7-777d7de1b299.JPG)

**Comment by digikeijs** [comment] 2019-03-24 19:35
@maghamed

**Comment by digikeijs** [comment] 2019-03-25 08:10
Looks like the issue is related to the address. When I create an order with a US address and add my product, on the first load it takes the wrong source/stock. When I change my state it suddenly gives the backorder message for the correct source / stock. 
![image](https://user-images.githubusercontent.com/34745091/54904056-b3099780-4edd-11e9-9162-8c1d9810e9a0.png)

Already changed the distance provider to offline calculation but that does not help.

**Comment by smoskaluk** [comment] 2019-03-25 10:52
Hi @digikeijs, I can't reproduce this issue, may you please give more details please.  Did you create separate Stores/Storeviews for your custom websites as well?

**Comment by digikeijs** [comment] 2019-03-25 10:54
@smoskaluk yes there are. Do you want to look in to my test environment? Can you then ping me on slack?

**Comment by smoskaluk** [comment] 2019-03-26 08:41
I can reproduce the issue when I place order from admin and qty of order items exceeds qty allocated on Default source for this product  - what is wrong - because inventory for that custom website set to custom stock with custom source assigned

**Comment by maghamed** [comment] 2019-03-26 13:19
@smoskaluk pls update steps to reproduce in to this ticket, as currently all your find outs are in comments

**Comment by digikeijs** [comment] 2019-03-26 13:26
@maghamed  @smoskaluk I updated the steps and added new screenshots

**Comment by ishakhsuvarov** [comment] 2019-04-02 16:49
@digikeijs Problem should be fixed with #2123 
Thanks for reporting

**Closed as completed by ishakhsuvarov** 2019-04-02 16:49 UTC
Labels: Bug, QA Verified

**Comment by digikeijs** [comment] 2019-04-02 19:46
Wow that's quick. Any idea when this will be available to download / install?

**Comment by smoskaluk** [comment] 2019-04-03 06:46
Hi @digikeijs , it's already merged into 2.3-develop branch

**Comment by maghamed** [comment] 2019-04-09 13:09
@digikeijs currently we are going to make next MSI delivery in approx 10 days from now
