### ISSUE TITLE
[Store Pickup] - Notify customer button

### ISSUE THREAD

**Issue by novikor** [magento/inventory#2107] opened 2019-03-24 16:59 UTC
### Description (*)
We need to create a button for order page which should notify the customer when the order is ready for pickup.

### Expected behavior (*)
If:
- An Order is placed using store pickup
- The selected pickup source has enough qty to fulfill the order

The button should be displayed.

On button click an email using a custom email template should be sent.

**Comment by swnsma** [comment] 2019-03-25 15:27
Does it duplicate of #2034 ?

**Closed as completed** 2019-03-25 15:28 UTC
Labels: Store Pickup
