### ISSUE TITLE
Cannot create shipment: Source item not found by source code: default and sku: [my-sku custom option]

### ISSUE THREAD

**Issue by adarshkhatri** [magento/inventory#2043] opened 2019-02-14 22:14 UTC
### Preconditions (*)

1. Magento Open Source 2.3
2. Inventory Source Enabled (By default? cannot disable)
3. https://imgur.com/uFZE5Y4

### Steps to reproduce (*)

1. Config product with Custom Options
2. Place order from frontend
3. Create Invoice
4. Create Shipment

### Expected result (*)

1. It should create shipment

### Actual result (*)

1. Source item not found by source code: default and sku: sols-imp-adult-t-shirt-Black-Full Colour - position 2.
2. No shipment created. No logs

PS I had reported this in https://github.com/magento/magento2/issues/21219, but they advised to report here.

**Comment by smoskaluk** [comment] 2019-02-18 16:40
Hi @adarshkhatri! Thank you for your report. I could not reproduce this issue, In my case I was able to create invoice and shipment without problems.

![image](https://user-images.githubusercontent.com/27818516/52965138-d1471980-33ac-11e9-9f63-59b80b233682.png)

![image](https://user-images.githubusercontent.com/27818516/52965037-87f6ca00-33ac-11e9-85c6-b6c58e0038c2.png)

May you please provide more information about your issue. Did you make new install of Magento 2.3.0 with MSI or you did upgrade from previous version of Magento? What version of MSI you have installed? Was it installation via composer or from git repository? May please give all details of custom option you created for your product as well.

**Comment by adarshkhatri** [comment] 2019-02-18 22:43
Hi @smoskaluk 

Thanks for reply. I had installed clean M2 2.3.0. 

Product has to be configurable with custom option.

Product detail: https://imgur.com/a/rCOasA9

Hope this helps.

Thanks.

**Comment by maghamed** [comment] 2019-02-19 00:35
This looks like a duplicate of issue https://github.com/magento-engcom/msi/issues/1912

Btw we have a pull request fixing this issue, which was not validated for other product types - https://github.com/magento-engcom/msi/pull/2012 

@adarshkhatri could you please check that fix in #2012 works for you?

Btw @smoskaluk is it really not reproducible for you? As the initial ticket created back to November 2018
Or you checked on Simple Product?

**Comment by adarshkhatri** [comment] 2019-02-19 01:55
@maghamed I don't see such fields in my shipping area.

Not sure if this will be helpful, but I will add the steps I took:

Initially I created a new source and stock. Assigned my new stock to newly created source. After that my frontend add to cart didn't work. It throws this error:

> [2019-02-19 01:43:09] main.CRITICAL: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'my_db.inventory_stock_4' doesn't exist, query was: SELECT `entity`.`sku`, `product_entity`.`entity_id` AS `product_id`, `attribute`.`attribute_code`, `entity_value`.`value` AS `value_index`, `attribute_label`.`value` AS `super_attribute_label` FROM `catalog_product_super_attribute` AS `super_attribute`
>  INNER JOIN `catalog_product_entity` AS `product_entity` ON product_entity.entity_id = super_attribute.product_id
>  INNER JOIN `catalog_product_super_link` AS `product_link` ON product_link.parent_id = super_attribute.product_id
>  INNER JOIN `eav_attribute` AS `attribute` ON attribute.attribute_id = super_attribute.attribute_id
>  INNER JOIN `catalog_product_entity` AS `entity` ON entity.entity_id = product_link.product_id
>  INNER JOIN `catalog_product_entity_int` AS `entity_value` ON entity_value.attribute_id = super_attribute.attribute_id AND entity_value.store_id = 0 AND entity_value.entity_id = entity.entity_id
>  LEFT JOIN `catalog_product_super_attribute_label` AS `attribute_label` ON super_attribute.product_super_attribute_id = attribute_label.product_super_attribute_id AND attribute_label.store_id = 0
>  LEFT JOIN `eav_attribute_option` AS `attribute_option` ON attribute_option.option_id = entity_value.value
>  INNER JOIN `inventory_stock_4` AS `stock` ON stock.sku = entity.sku WHERE (super_attribute.product_id = 1) AND (attribute.attribute_id = '93') AND (stock.is_salable = 1) ORDER BY `attribute_option`.`sort_order` ASC
>  {"exception":"[object] (Zend_Db_Statement_Exception(code: 42): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'my_db.inventory_stock_4' doesn't exist, query was: SELECT `entity`.`sku`, `product_entity`.`entity_id` AS `product_id`, `attribute`.`attribute_code`, `entity_value`.`value` AS `value_index`, `attribute_label`.`value` AS `super_attribute_label` FROM `catalog_product_super_attribute` AS `super_attribute`
>  INNER JOIN `catalog_product_entity` AS `product_entity` ON product_entity.entity_id = super_attribute.product_id
>  INNER JOIN `catalog_product_super_link` AS `product_link` ON product_link.parent_id = super_attribute.product_id
>  INNER JOIN `eav_attribute` AS `attribute` ON attribute.attribute_id = super_attribute.attribute_id
>  INNER JOIN `catalog_product_entity` AS `entity` ON entity.entity_id = product_link.product_id
>  INNER JOIN `catalog_product_entity_int` AS `entity_value` ON entity_value.attribute_id = super_attribute.attribute_id AND entity_value.store_id = 0 AND entity_value.entity_id = entity.entity_id
>  LEFT JOIN `catalog_product_super_attribute_label` AS `attribute_label` ON super_attribute.product_super_attribute_id = attribute_label.product_super_attribute_id AND attribute_label.store_id = 0
>  LEFT JOIN `eav_attribute_option` AS `attribute_option` ON attribute_option.option_id = entity_value.value
>  INNER JOIN `inventory_stock_4` AS `stock` ON stock.sku = entity.sku WHERE (super_attribute.product_id = 1) AND (attribute.attribute_id = '93') AND (stock.is_salable = 1) ORDER BY `attribute_option`.`sort_order` ASC
>  at /vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:235, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'my_db.inventory_stock_4' doesn't exist at /vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:228)"} []


Then, I deleted the source and was able to add product to cart. My default source is active. 

And when I try to ship the item receive above error message. 

**PS I am not managing stock from store config.**

It would be better to have fresh install request like Magento core allows us to (vanilla instance), with MSI so that I could confirm it's the real issue and not only in my instance.

Thanks.

**Comment by adarshkhatri** [comment] 2019-02-19 02:14
And after applying above https://github.com/magento-engcom/msi/pull/2012, it now gives similar exception:

> Source item not found by source code: Store and sku: sols-imp-adult-t-shirt-Black.

**Comment by smoskaluk** [comment] 2019-02-19 08:41
@maghamed yes, from initial description I didn't understand that issue about configurable product and tried to reproduce with simple product with custom option. 
With configurable product it reproducing, and as you already mentioned, it duplicate https://github.com/magento-engcom/msi/issues/1912.

**Comment by smoskaluk** [comment] 2019-02-19 09:59
Hi @adarshkhatri ! I've tried fix in PR https://github.com/magento-engcom/msi/pull/2012 , and it was working well. 

![image](https://user-images.githubusercontent.com/27818516/53006086-39454080-343d-11e9-80da-30c5fbce61d7.png)
I wonder, may be it didn't work in your case because you have 0 quantity for your child products of configurable product? Please recheck

![image](https://user-images.githubusercontent.com/27818516/53006376-c8525880-343d-11e9-8dc9-dbe3513b1d36.png)

**Comment by adarshkhatri** [comment] 2019-02-20 04:33
@smoskaluk 

They are zero because I am not managing stocks.

**Comment by VitaliyBoyko** [comment] 2019-02-20 09:39
@smoskaluk @maghamed 
As far as I have understood from comments, this issue is not a duplicate of  #1912. 
We need to disable source selection when manage stock is off on the shipment.
Right?

**Comment by VitaliyBoyko** [comment] 2019-02-20 12:13
@adarshkhatri what the reason to use multiple sources if managing stock is disabled?

**Comment by adarshkhatri** [comment] 2019-02-20 22:58
@VitaliyBoyko 

Exactly, I am not managing stock but MSI is enabled by default.

Also, I might want to manage stock for specific item in future. In this case I would still want to have MSI enabled.

PS, I haven't created any source, there is just 1 available ie. "default".

Thanks.

**Comment by adarshkhatri** [comment] 2019-03-21 01:19
It looks like there is check in place:

            if (!$stockItemConfiguration->isManageStock()) {
                //We don't need to Manage Stock
                continue;
            }

https://github.com/magento-engcom/msi/blob/2.3-develop/app/code/Magento/InventorySourceDeductionApi/Model/SourceDeductionService.php#L76

I think solution would be to find the list by `product id` instead of sku. I see that when creating order `Magento` adds `Custom Option` to the configurable item, when it has custom option

**For example:** 
Config item's sku: Config Item with Custom Option
Child Item: Config Item with Custom Option-Black-First

But when order created:
![db](https://user-images.githubusercontent.com/8390252/54662973-eb068880-4b33-11e9-83a7-fdfb5f0d0fc0.png)

Because of this, system will never find the product.

       //namespace Magento\InventorySourceDeductionApi\Model\GetSourceItemBySourceCodeAndSku

        $searchCriteria = $this->searchCriteriaBuilder
            ->addFilter(SourceItemInterface::SOURCE_CODE, $sourceCode) //default
            ->addFilter(SourceItemInterface::SKU, $sku) //Config Item with Custom Option-Black-First Custom Option
            ->create();
        $sourceItemsResult = $this->sourceItemRepository->getList($searchCriteria);

**I think, finding the source item by `product id` will always find the product if it exist.**

**Comment by adarshkhatri** [comment] 2019-03-21 01:25
Also on my further investigation, I found this:

```
class Magento\InventorySourceDeductionApi\Model\SourceDeductionService

/**
     * @inheritdoc
     */
    public function execute(SourceDeductionRequestInterface $sourceDeductionRequest): void
    {
        $sourceItems = [];
        $sourceCode = $sourceDeductionRequest->getSourceCode();
        $salesChannel = $sourceDeductionRequest->getSalesChannel();

        $stockId = $this->getStockBySalesChannel->execute($salesChannel)->getStockId();
        foreach ($sourceDeductionRequest->getItems() as $item) {
            $itemSku = $item->getSku();
            $qty = $item->getQty();
            $stockItemConfiguration = $this->getStockItemConfiguration->execute(
                $itemSku,
                $stockId
            );

            if (!$stockItemConfiguration->isManageStock()) {
                //We don't need to Manage Stock
                continue;
            }

            $sourceItem = $this->getSourceItemBySourceCodeAndSku->execute($sourceCode, $itemSku);
            if (($sourceItem->getQuantity() - $qty) >= 0) {
                $sourceItem->setQuantity($sourceItem->getQuantity() - $qty);
                $sourceItems[] = $sourceItem;
            } else {
                throw new LocalizedException(
                    __('Not all of your products are available in the requested quantity.')
                );
            }
        }

        if (!empty($sourceItems)) {
            $this->sourceItemsSave->execute($sourceItems);
        }
    }
```

`$stockItemConfiguration->isManageStock()` for config item with custom option always returns `1`. I confirm, I am not managing stock for child and parent. 

I also confirm, in my different instance, I have not created any STOCK SOURCE yet.
Manage Source: Default
Manage Stock: Default Stock

![sourcce](https://user-images.githubusercontent.com/8390252/54728858-56a03280-4bd4-11e9-9ed6-c8d17e8c2d4f.png)
![stock](https://user-images.githubusercontent.com/8390252/54728859-5738c900-4bd4-11e9-8915-fc0b4b83dae8.png)

**Comment by mrtuvn** [comment] 2019-04-11 09:43
Hello guys any updates on this problem ? Today i faced same issue like this

**Comment by mrtuvn** [comment] 2019-04-11 09:55
I got issue with custom option of product configurable
Source item not found by source code: default and sku: AdminConfig-Black-Test.
AdminConfig is SKU of parent
Black is child attribute
Test is custom option SKU

**Comment by VitaliyBoyko** [comment] 2019-05-01 07:16
Fixed in 2.3 develop

**Closed as completed by VitaliyBoyko** 2019-05-01 07:16 UTC
Labels: QA Verified

**Comment by mrtuvn** [comment] 2019-05-02 03:17
@VitaliyBoyko can you add reference pull request related with this fix

**Comment by teodorpav** [comment] 2019-05-03 17:41
I have the same issue on 2.3.1 with simple product without any custom options. The issue is when the products are imported but 'Salable Quantity' is 0. If you Edit/Save the product the issue will be fixed.

**Comment by avoelkl** [comment] 2019-06-21 09:48
I can confirm I just encountered the same issue as @teodorpav above with Magento Open Source 2.3.1 and imported products. Saving the product in the backend solves the issue

**Comment by tschirmer** [comment] 2021-05-12 07:22
We had this happen when a sku was put in , ordered, then changed before shipping. The shipment then tries to find an skus that is no longer being indexed (and nor should it be). The index would be far better off running on product entity_ids so this kind of this doesn't happen.

**Comment by tschirmer** [comment] 2021-05-12 07:23
This has happened on our 2.3.6-p1 version with the latest msi installed.

The best solution we've found is to block out the sku field on edit, so it's treated like an id that can't be edited. 

This also doesn't work well if skus have spaces in them
