### ISSUE TITLE
Fix failure of functional test Magento\FunctionalTestingFramework.functional\MSI_Sort_Order_Tests.AdminSelectDeselectManipulationsInManageStocksGridTest

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1802] opened 2018-10-17 11:44 UTC
Fix failure of functional test http://10.234.148.146:8080/job/Functional-Tests-CE/1760 
Magento\FunctionalTestingFramework.functional\MSI_Sort_Order_Tests.AdminSelectDeselectManipulationsInManageStocksGridTest  -  unknown error: Element <button class="action-primary action-accept" type="button" data-role="action">...</button> is not clickable at point (829, 158). Other element would receive  
![image](https://user-images.githubusercontent.com/27818516/47084047-18fd3f00-d21b-11e8-826c-22d4e97b8d17.png)

**Comment by IvanPletnyov** [comment] 2018-10-17 13:46
Manually I've not reproduced yet this fail, I've run it's test but it passed

**Comment by okorshenko** [comment] 2019-06-13 20:11
@smoskaluk please revalidate

**Comment by ishakhsuvarov** [comment] 2019-06-17 20:00
Test seems to be passing at the moment. closing.

**Closed as completed by ishakhsuvarov** 2019-06-17 20:00 UTC
Labels: MFTF
