### ISSUE TITLE
Default stock: 1 shown next to qty in Admin?

### ISSUE THREAD

**Issue by cscd98** [magento/inventory#2270] opened 2019-05-22 17:59 UTC
I've emptied my stock_reservation and inventory_shipment_source table on a development machine.

In the back end Catalog->Grid the default stock says: 1 but in inventory_source_item it says 52 for that sku??

Qty
52.0000

Default Stock: 1

**Comment by ishakhsuvarov** [comment] 2019-06-06 04:02
Hi @craigcarnell 

Looks like we don't have enough information to reliably reproduce the issue you described. In any case, manually emptying tables may lead to undesired effects.

Please clarify the details on this problem and we will try to investigate what's happening.

Thanks

**Comment by sidolov** [comment] 2020-02-03 21:06
@craigcarnell I'm closing the issue since we haven't additional details to reproduce it.

**Closed as completed by sidolov** 2020-02-03 21:06 UTC
