### ISSUE TITLE
Inventory source disappears from UI after assign / unassign operation on Product Edit

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/inventory#2066] opened 2019-03-05 12:02 UTC
### Preconditions (*)
1. Magento 2.3.0 installed from Composer
2. MSI installed (by default with Magento 2.3.0 CE)

### Steps to reproduce (*)
1. Admin Panel: Enter "Add product" form
2. Click "Assign sources" button, wait for pan to open
3. Select one of the sources (eg. "Default"), click "Done"
4. Unassign selected source with thrash icon
5. Click "Assign sources" button again, wait for pan to open

### Expected result (*)
1. After unassigning the source should be back available

### Actual result (*)
1. You cannot see / reassign the source you've just unassigned.

### Side notes
@magterskine  Confirmed / reproduced the issue during #MageTestFest in Florence.

**Comment by lbajsarowicz** [comment] 2019-03-08 10:14
The problem occurs only when removing last element from dynamic grid. It's caused by Magento's app/code/Magento/Ui/view/base/web/js/dynamic-rows/dynamic-rows-grid.js:setToInsertData method ( https://github.com/magento-engcom/msi/blob/cb1e674d0bc79b8937671d8b6bc33f4cb1694dcf/app/code/Magento/Ui/view/base/web/js/dynamic-rows/dynamic-rows-grid.js#L50-L68 ). If `insertData.length` is 0, the data is not saved, so we cannot reassign previously removed source.

**Comment by deiserh** [comment] 2019-03-26 18:30
Because of to less time I add my findings here so somebody else can continue with this ticket.

Its a valid behavor that the function setToInsertDate is length 0, because thats removing the assigned item.

The problem is, that in the providor.js (app/code/Magento/Ui/view/base/web/js/grid/provider.js) a reload loads the sources by a filter query. 

If two items in the list and one will be removed everything is fine but if only one Item is in the assigned list and its removed for some reasen the filter query will be updated after the reload. So if you assigne another source again the filter is correct again and the missing source appears.

**Comment by mypav** [comment] 2019-05-17 15:43
I can't reproduce this problem by specified preconditions.

**Comment by lbajsarowicz** [comment] 2019-05-17 15:45
Run MFTF test #2069 that covers the issue

**Closed as completed** 2019-09-20 05:18 UTC
