### ISSUE TITLE
Product stock Import timeout

### ISSUE THREAD

**Issue by brideo** [magento/inventory#2059] opened 2019-03-01 07:55 UTC
### Preconditions (*)

1. Magento 2.3 Installed
2. Magento MSI enabled
3. Large import stock file
4. Indexes set to "real-time" 

### Steps to reproduce (*)

1. Go to admin 
2. System > Import > Stock Sources
3. Add large files with composite products

### Expected result (*)

1.  Import should run

### Actual result (*)

1. Import times out and causes a memory leak 

### Workaround

Set indexes to scheduled 

Related: https://github.com/magento/magento2/issues/21526

**Comment by VitaliyBoyko** [comment] 2019-04-16 06:21
Hi @brideo 
I've tested the issue and cannot reproduce it on my environment.

Could you please check your `memory_limit` configuration. The import took around 56.43 MiB of memory and about 3 seconds per 100 rows. In case if the config least you should increase it or decrease the bunch size.
 Import of 39k (medium profile of performance fixtures) rows has taken 676 seconds, max memory usage has been 56.49 MiB.

```
[2019-04-15 20:14:16] main.DEBUG: time start 1555359256 [] []
[2019-04-15 20:14:16] main.DEBUG: bunch-size 100 [] []
[2019-04-15 20:14:19] main.DEBUG: memory 56.43 MiB [] []
[2019-04-15 20:14:19] main.DEBUG: time end 1555359259 [] []
```

Also, I've tested the issue with indexers set to 'update by schedule'. The import took around 46.48 MiB of memory and about 1 second per 100 rows. I believe the difference between 56.43 MiB and 46.48 MiB is not crucial.
Let me know if you have any questions. Thanks!

**Comment by ishakhsuvarov** [comment] 2019-04-23 15:23
Hi @brideo 
Multiple people have trie reproducing the issue in question so far with no success. I'm closing the ticket for now.

Please feel free to reopen if the issue persists for you and maybe you find a specific step to make it reproducible.

Thanks!

**Closed as completed by ishakhsuvarov** 2019-04-23 15:23 UTC
Labels: Award: special achievement, needs update, Not Reproduced, MSI 1.1.2 Release
