### ISSUE TITLE
Source Selection Algorithm lose fractional part of ordered value

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#1660] opened 2018-09-19 18:09 UTC
Preconditions:

1. Custom Stock created
2. Two Custom Sources created and assigned to newly created Stock
3. Newly Created Stock assigned to Main Website
4. Create product and add Source Items for both custom sources (Qty = 10 and Qty = 20)

Steps to reproduce:

1. place an order with the newly created product with Qty = `20.5` 
2. go to magento admin panel, Sales -> Order -> Ship
3. Run Source Selection Algorithm

Actual Result:
Fractional part is lost

**Comment by maghamed** [comment] 2018-09-19 18:36
maybe we have additional issues with SSA.

Did not have time to test many cases. B

**Comment by phoenix128** [comment] 2018-09-19 19:56
@maghamed , I was not able to reproduce this. I tried several scenarios withtout success.

**Comment by p-bystritsky** [comment] 2018-09-20 07:24
Issue reproduced, working on it.

**Comment by p-bystritsky** [comment] 2018-09-20 14:01
I think this issue can be closed as https://github.com/magento-engcom/msi/issues/1664 is more correct.

**Closed as completed** 2018-09-25 11:05 UTC
Labels: Award: special achievement
