### ISSUE TITLE
Magento 2.3 - Multi-Source Inventory discrepancy with stock at source and salable quantity

### ISSUE THREAD

**Issue by karthi5053** [magento/inventory#1971] opened 2019-01-10 10:13 UTC
Thanks for incorporating, Multi source Inventory module for magento. But, we are facing some issues while incorporating and using this module on a realtime scenario.

Preconditions (*)

1) Magento 2.3.0 CE
2) PHP 7.1

Steps to reproduce (*)

1) Create a Inventory source under (Store-> Inventory-> Sources) as "NY-Warehouse".
2) Create a stock as "NY-Warehouse Stock" under (Store-> Inventory-> Stocks), and assign to a Sales Channels for a website.
3) Now, for a simple product (Eg : SKU code - 24-MG02), assign this source, NY-Warehouse with stock as 100, unassign "Default Source".
    Here, 
        Quantity at source is 100,
        salable quantity is 100 
    is shown in catalog grid, which is fine as shown in image s1.png.
![s1](https://user-images.githubusercontent.com/7961427/50961690-67566d00-14ee-11e9-97c5-86df12e0dbb3.png)

4) Now place, an order with 20 qty for the sku 24-MG02.
    Here, 
         Quantity at source remains as 100,
         salable quantity is 80, since we placed an order with qty 20. Refer s2.png
![s2](https://user-images.githubusercontent.com/7961427/50961692-67566d00-14ee-11e9-9412-3cc0de13a846.png)

5) In realtime scenario, Sources means physical warehouse, so we may get latest stock from warehouse on a time to time basis.
   Consider, there is some new stocks arrived to warehouse for the sku : 24-MG02 and they increased the stock for the sku from 100 to 200, which can sold in the website. Now, we update the stock as source for "NY-Warehouse" to 200.
    Here,    
        Quantity at source remains as 200,
        however, salable quantity is 180. Refer s3.png
![s3](https://user-images.githubusercontent.com/7961427/50961693-67ef0380-14ee-11e9-9f10-7253f15b6b03.png)

Expected result (*):

Upon, updating the stock at source for "NY-Warehouse" to 200, we expect the 200 quantity i.e salable quantity can be allowed for the users to place orders in website. But, we allowed to purchase upto 180 qty only. The remaining 20 qty is locked as the, order in warehouse for fullfillment. 
If the order is fullfilled i.e invoice and shipments are created,
    Quantity at changed to 180,
    Salable quantity is 180. Refer s4.png
![s4](https://user-images.githubusercontent.com/7961427/50961694-68879a00-14ee-11e9-8ff2-36950884416d.png)

Until, the placed orders is fullfilled, the salable qty is calculated by stock at source - pending orders in website.
    i.e 200 - 20 = 180.

In realtime scenario, we expect 200 quantity, that can be sold in website, as 200 qty is available in the warehouse, because warehouse will deduct the on-hand stock after shipping the order from their end.

Regards,
Karthi Kumar.

**Comment by karthi5053** [comment] 2019-01-28 10:04
Hi,

Can we have an update on this?

Regards,
Karthi Kumar.

**Comment by maghamed** [comment] 2019-02-10 20:35
hi @karthi5053 ,

Sorry for the late reply. I'll provide feedback as soon as MSI 1.1.0 release would be done.  Hopefully, this will happen during this week.

Too many resources currently dedicated to the project release. 
Thanks for understanding

**Comment by karthi5053** [comment] 2019-03-14 07:54
Hi,

Can we have an update on this?

Regards,
Karthi Kumar.

**Comment by maghamed** [comment] 2019-03-30 00:05
hey @karthi5053 

sorry for late reply. Regarding the case, you described in the ticket. Currently, it is expected behavior which complies with the desirable state of new Inventory workflows. 
MSI introduces two types of Quantities:

1. Quantity on Source (real quantity of product allocated on physical warehouse/distribution center/brick and mortar store)
2. Salable Quantity - aggregated quantity of product among all the Sources assigned to particular Stock (virtual aggregation).

You can read more about this here - https://docs.magento.com/m2/ce/user_guide/catalog/inventory-management.html

In your case you have just one source assigned to `NY-Warehouse Stock` Stock (this is the simplest case, which we call Single Source mode). But potentially there could be many sources assigned, so that when the order is placed in the scope of given Stock the system is unaware which source (or bunch of sources) would be used to fulfill that particular order.  Moreover this decision making (we call it source selection) could be quite costly from the performance standpoint if there are a lot of sources and porducts in the shopping cart, as the number of permutations and variations of order fulfillment is growing exponentially. Thus, to prevent any performance degradation at the time of order placement, but along with that prevent merchants from overselling Magento places the Reservation istead of making direct Source deduction. Here you can read more about Reservation entity, what does it represent and how it's implemented https://github.com/magento-engcom/msi/wiki/Salable-Quantity-Calculation-and-Mechanism-of-Reservations

The real Source Deduction happens when merchant processes an order and creates shipment. Before the Shipment step MSI introduces new step - Source Selection Algorithm (SSA), which supposed to provide a suggestion which source(-s) should be used to fulfill given order. When merchant confirms that suggestion and creates shipment - Magento proceeds with Quantity deduction on the level of particular Source.

So, getting back to your example, when the order is placed for 20 items - Magento creates reservation which impacts salable quantity (which is now deducted by 20). But the order is still not shipped to customer. That means that 20 items are still stored on the warehouse and awaiting to be delivered. That's why Source Qty 100 is correct. Moreover, if you would like to introduce more sophisticated inventory related customization, like Inventory Procurement and make a prediction when you need to order more products from supplier to particular Source - that would be useful.

Now the step 5 which you described:
>Consider, there is some new stocks arrived to warehouse for the sku : 24-MG02 and they increased the stock for the sku from 100 to 200, which can sold in the website. Now, we update the stock as source for "NY-Warehouse" to 200.

From Magento standpoint on that step you supplied the Source with additional 100 items, and the system currently represents the correct product quantity allocated on that Source - 200 items all together. But along with that you still did not complete the Order created on previous step, so 20 items are not shipped to customer yet. They are reserved for that customer and awaiting shipment. They occupy space in the warehouse and we can't sell them to somebody else, because in that case we could not fulfill our initial order. That's what Salable Quantity = 180 means.

**Comment by maghamed** [comment] 2019-03-30 00:12
if you have integration with 3rd party ERP systems and you make the source selection and Source Deduction there, but not in Magento. That means that this external system is your Source of Truth, but not Magento. Thus, having periodical synchronization on the level of inventory and accepting correct Source data from that system - that's your responsibility to customize Magento the way to make a decision how to process already open reservations (like in your example, the one for -20 items). Because Magento, in this case, knows nothing whether that order has already been processed and quantity compensated (order shipped) or not. And here could not be out of the box solution, because this handling would be dictated by business workflow you have:
- whether the orders are handled externally, and the external system dictates you to overwrite both Source Quantity and Salable Quantity (the external system is a source of truth both for Order Management and Inventory management)
- whether the external system just sends you correct Source Quantities, but you still have to handle already placed orders in Magento (the external system is a source of truth for Inventory management only)

@karthi5053 let me know if that makes sense for you

**Comment by karthi5053** [comment] 2019-04-02 11:53
Hi Maghamed, 

Thank you for your detailed explanation on this. 

As it stands, MSI module works quite well when the stock and order fullfillment are managed within magento. But when, it comes to integrating Magento with external ERP/Warehouses system, we may face such issues.

Regards,
Karthi Kumar.

**Comment by maghamed** [comment] 2019-04-03 11:01
Hey @karthi5053 ,
That’s not an issue, but by desig behavior. Moreover you could consider that  as  a feature for your integration as Magento introduces explicit extension point  for customization, and you literally need  to customize just one place in the code to make your customization work properly in accordance to your business scenarios.  You can look at this interface https://github.com/magento-engcom/msi/blob/2.3-develop/app/code/Magento/InventorySalesApi/Api/PlaceReservationsForSalesEventInterface.php and places in code where it’s used. Depending on how you are going to integrate Magento with external ERP system  - you customization will look differently, you may even skip reservation placement at all, if needed.

**Comment by maghamed** [comment] 2019-04-03 11:20
Btw you can watch presentation by @vadimjustus who is talking about similar customizations when Magento syncing up with ERP   https://youtu.be/RoIEaoVm4mU

**Closed as completed** 2019-04-06 08:31 UTC
