### ISSUE TITLE
Fatal error in assign sources on product level

### ISSUE THREAD

**Issue by jorgb90** [magento/inventory#2129] opened 2019-04-02 12:20 UTC
### Preconditions (*)
1. Magento 2.3.1 CE with MSI
2. ElasticSearch

### Steps to reproduce (*)
1. In the backend have a product with two sources
2. Open the product and go to Assign Sources
3. In the overlay the fatal error occurs.

Fatal error: Method Magento\Ui\TemplateEngine\Xhtml\Result::__toString() must not throw an exception, caught Error: Call to undefined method Magento\Framework\Api\Search\SearchResult::isLoaded() in /home/xxxx/public_html/vendor/magento/module-ui/Controller/Adminhtml/Index/Render.php on line 0

### Expected result (*)
1. See a list of assigned and unassigned sources.

### Actual result (*)
1. An overlay with the fatal error.

![assignsources](https://user-images.githubusercontent.com/7294081/55403157-7ed54d00-5555-11e9-8ea2-5b76f313ac9a.png)

**Comment by smoskaluk** [comment] 2019-04-03 12:42
Hi @jorgb90 , I couldn't reproduce this issue, may you please give more details about it.

**Comment by jorgb90** [comment] 2019-04-03 12:57
@smoskaluk 

I just now that we are getting this error:

**Comment by jorgb90** [comment] 2019-04-03 12:59
@smoskaluk 
I just know that we are getting this error on a Magento application running in production mode. If we visit stores/source or stores/stocks in the backend or just try to assign sources on the product page we get it.

**Edit:**
I can confirm now that ElasticSearch has nothing to do with it. We disabled it and we are still getting this error.

**Comment by maghamed** [comment] 2019-04-03 20:57
@jorgb90 do you have any 3rd party extensions or customization, as on pure Magento 2.3.1 + MSI the issue is not reproducible

**Comment by jorgb90** [comment] 2019-04-05 07:48
@maghamed It is running on a production environment so yes there are 3rd party extensions installed, but none have something to do with listing sources and stocks in the back-end. The only customization I have done to MSI is this one #2113. All other functionalities like assigning sources through the productgrid are working fine.

BTW How do I know if I have the latest version of MSI installed?

**Comment by smoskaluk** [comment] 2019-04-08 10:29
@jorgb90 If you installed your Magento from repo.magento.com - then you have latest released MSI version.
Please try to reproduce your issue on clean fresh Magento 2.3.1 installation - without any 3rd party modules

**Comment by ishakhsuvarov** [comment] 2019-05-07 21:30
@jorgb90 Closing this ticker for now as we were unable to reproduce it at this point. Please feel free to reopen if you have any additional information on this.

Thanks

**Closed as completed by ishakhsuvarov** 2019-05-07 21:30 UTC
Labels: Not Reproduced
