### ISSUE TITLE
Problem with indexer

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#2770] opened 2020-01-03 09:33 UTC
### Preconditions (*)

1. Install fresh Magento with MSI 1.1-develop

### Steps to reproduce (*)

1. Run CLI command bin/magento indexer:reindex twice
2. Go to Admin -> System -> Index managment 

### Expected result (*)

1. All indexer are green

### Actual result (*)

1. Indexers 'Category Products' and 'Catalog Rule Product' invalidated 

![image](https://user-images.githubusercontent.com/27818516/71716275-d40ff900-2e1c-11ea-8278-6eaf2b010ba1.png)

**Comment by nmalevanec** [comment] 2020-01-10 08:38
@smoskaluk Not able to reproduce this issue. Looks like has been fixed in https://github.com/magento/inventory/commit/b295b7b6cc3b9a0d3311fd348b3b13f3fc5a0858
Could you please re-check?

**Closed as completed** 2020-01-10 08:46 UTC
