### ISSUE TITLE
Bulk Inventory Transfer from backend doesn't work with numerical skus

### ISSUE THREAD

**Issue by HS-Fachmarkt** [magento/inventory#1980] opened 2019-01-14 15:46 UTC
### Preconditions
1.    Magento Commerce 2.3.0
2.    Magento MSI

### Steps to reproduce
1. Create two inventory sources
2. Create or use a product with only digits in sku. Assign it to any Source and give it Quantity.
3. in Backend Catalog/Products: check the product and do the "Transfer Inventory to Source" action

### Expected result
1. Source should get changed

### Actual result
1. I get a blank page and a PHP Fatal error in Apache error log.
`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Magento\\InventoryCatalog\\Model\\ResourceModel\\BulkInventoryTransfer::getSourceItemData() must be of the type string, integer given, called in /MAGEROOT/web/vendor/magento/module-inventory-catalog/Model/ResourceModel/BulkInventoryTransfer.php on line 116 and defined in /MAGEROOT/web/vendor/magento/module-inventory-catalog/Model/ResourceModel/BulkInventoryTransfer.php:85, referer: https://mage2.local/admin/inventorycatalog/inventory/bulkTransfer/key/aeb29925ae2ec548e87781e75e3314eae32dce9b7fe64edc47c9aa76829442e9/
Stack trace:, referer: https://mage2.local/admin/inventorycatalog/inventory/bulkTransfer/key/aeb29925ae2ec548e87781e75e3314eae32dce9b7fe64edc47c9aa76829442e9/
#0 /MAGEROOT/web/vendor/magento/module-inventory-catalog/Model/ResourceModel/BulkInventoryTransfer.php(116): Magento\\InventoryCatalog\\Model\\ResourceModel\\BulkInventoryTransfer->getSourceItemData(1015050, 'warehouse_poz'), referer: https://mage2.local/admin/inventorycatalog/inventory/bulkTransfer/key/aeb29925ae2ec548e87781e75e3314eae32dce9b7fe64edc47c9aa76829442e9/
#1 /MAGEROOT/web/vendor/magento/module-inventory-catalog/Model/ResourceModel/BulkInventoryTransfer.php(208): Magento\\InventoryCatalog\\Model\\ResourceModel\\BulkInventoryTransfer->transferInventory(1015050, 'warehouse_poz', 'store_poz'), referer: https://mage2.local/admin/inventorycatalog/inventory/bulkTransfer/key/aeb29925ae2ec548e87781e75e3314eae32dce9b7fe64edc47c9aa76829442e9/
#2 /MAGEROOT/web/vendor/magento/mo in /MAGEROOT/web/vendor/magento/module-inventory-catalog/Model/ResourceModel/BulkInventoryTransfer.php on line 85, referer: https://mage2.local/admin/inventorycatalog/inventory/bulkTransfer/key/aeb29925ae2ec548e87781e75e3314eae32dce9b7fe64edc47c9aa76829442e9/
`

### Newbie fix
![grafik](https://user-images.githubusercontent.com/3403923/51123124-b4528000-181b-11e9-9381-2fec0bfdac15.png)
By deleting the typehint string for the sku in this functions, the function works as expected.

**Comment by maghamed** [comment] 2019-01-15 03:53
Thanks for the bug report @HS-Fachmarkt. 

I think the better way to fix the issue above is to add explicit type casting to string for SKU.

**Comment by maghamed** [comment] 2019-01-15 15:30
hey @HS-Fachmarkt  the issue is fixed and merged into 2.3-develop branch

so that it would be released in the upcoming MSI Patch release

**Closed as completed** 2019-02-10 20:04 UTC
