### ISSUE TITLE
'Order is ready for pickup' email template can't be loaded  

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#2686] opened 2019-11-05 09:31 UTC
Navigate in admin Marketing -> Emails templates
Click 'Add New Template' button
Select in drop-down tepmlates list 'Order is ready for pickup' and click 'Load Template'

![image](https://user-images.githubusercontent.com/27818516/68195462-9418cb00-ffbf-11e9-86de-e07026f884a5.png)

Exeption log:
[2019-11-05 09:28:01] main.CRITICAL: Unable to unserialize value. Error: Syntax error {"exception":"[object] (InvalidArgumentException(code: 0): Unable to unserialize value. Error: Syntax error at /msi/lib/internal/Magento/Framework/Serialize/Serializer/Json.php:39)"} []

**Comment by nmalevanec** [comment] 2019-11-11 09:07
@smoskaluk, I'm not able to reproduce this issue. Could you please add more details?
![Peek 2019-10-16 11-18](https://user-images.githubusercontent.com/11520943/68574810-67f3c300-0473-11ea-86e2-ff2116e5573d.gif)

**Comment by ishakhsuvarov** [comment] 2019-11-14 15:28
@nmalevanec It was fixed in https://github.com/magento/inventory/commit/75187b8eacaccb160ed74ab83ccba4940b6cc839

**Closed as completed by ishakhsuvarov** 2019-11-14 15:28 UTC
Labels: Store Pickup
