### ISSUE TITLE
Product Salable quantity increase after the shipment was created.

### ISSUE THREAD

**Issue by tranhoangthien1990** [magento/inventory#2754] opened 2019-12-12 09:52 UTC
Dear,
I'm facing an issue with product salable quantity value.

**Preconditions (*)**
1. Magento EE - 2.3.3 with sample data.

**Steps to reproduce**
1. Change the stock index mode to "Update by Schedule".
2. Create a new order with any product.
3. Come to the Admin board and check the product stock data, please focus on quantity and salable quantity.
3. Create a shipment for this order.
4. Come to the product grid and check the product stock data again.

**Expected result**
1. The product quantity decrease due to the quantity was shipped, the salable quantity doesn't change

**Actual result**
1. The product quantity decrease due to the quantity was shipped, the salable quantity increased.

**The root cause:**

The qty column of the table "cataloginventory_stock_status" doesn't change immediately, we need to reindex manually to update it.

So, any solution for it, because if the salable quantity doesn't change immediately, the customer can purchase the product, but the store doesn't enough stock (salable quantity will be negative after reindex).

**Comment by ishakhsuvarov** [comment] 2019-12-12 16:07
Hi @tranhoangthien1990 

Looks like PR https://github.com/magento/inventory/pull/2740 would fix the issue, as it targets the root cause you have mentioned. We are working to get this merged shortly.

**Closed as completed** 2019-12-13 15:51 UTC
