### ISSUE TITLE
MSI fails creditmemo when refunding numeric SKU

### ISSUE THREAD

**Issue by kassner** [magento/inventory#2554] opened 2019-09-12 13:16 UTC
### Preconditions

1. Create two products with SKUs `12345` and `12345-test`;
2. Make sure Magento is configured to return products back to stock on refunds;
3. MySQL 5.7.25 and PHP 7.2.22;

### Steps to reproduce

1. Place an order for the product with SKU `12345`;
2. Invoice the order;
3. Refund the order;

### Expected result

Credit memo is created.

### Actual result

1. Error message saying `The credit memo couldn't be saved.`;

### Deep dive

Tracing the exception I got:

```
Notice: Undefined index: 12345-test in /var/www/magento/vendor/magento/module-inventory-source-selection-api/Model/Algorithms/Result/GetDefaultSortedSourcesResult.php on line 123
```

This is caused by [this line](https://github.com/magento/inventory/blob/28ffcb48b596b97b5c8e262270a1432923b727d8/app/code/Magento/InventorySourceSelectionApi/Model/Algorithms/Result/GetDefaultSortedSourcesResult.php#L108), because [the way array_key behaves](https://3v4l.org/VeEJ3) with numeric string as keys. This is passed as an integer down to `GetInStockSourceItemsBySkusAndSortedSource`, which ends up building a SQL like:

```
select * from catalog_product_entity where `sku` IN(12345)
```

Relying in [another MySQL behaviour](http://sqlfiddle.com/#!9/1c01c9/1/0), it will return both rows instead of the requested SKU.

**Comment by kassner** [comment] 2019-09-12 13:17
I have a [small patch](https://gist.github.com/kassner/3542addaac051acd72f8b7d369052260) for it already, will send a PR later.

**Comment by ishakhsuvarov** [comment] 2019-09-13 00:30
Thanks @kassner 

We would really appreciate a PR!

**Comment by kolaente** [comment] 2019-11-07 13:01
@kassner Any update on this regarding a PR? We also hit this issue in one of our shops.

**Comment by kassner** [comment] 2019-11-07 14:36
@kolaente I couldn’t manage to prepare a test case in a timely manner, but you can use this patch if it’s too critical: https://gist.github.com/kassner/3542addaac051acd72f8b7d369052260

**Comment by joinso** [comment] 2019-11-11 18:59
Hi!

The patch does not work:

 PHP Fatal error:  Uncaught Error: Cannot instantiate interface Magento\\Customer\\Api\\LinkTokenManagerInterface in /var/app/current/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:116\nStack trace:\n#0 /var/app/current/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject('Magento\\\\Custome...', Array)\n#1 /var/app/current/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Magento\\\\Custome...')\n#2 /var/app/current/vendor/magento/module-customer/Model/AccountManagement.php(438): Magento\\Framework\\ObjectManager\\ObjectManager->get('Magento\\\\Custome...')\n#3 /var/app/current/generated/code/Magento/Customer/Model/AccountManagement/Interceptor.php(14): Magento\\Customer\\Model\\AccountManagement->__construct(Object(Magento\\Customer\\Model\\CustomerFactory), Object(Magento\\Framework\\Event\\Manager\\Proxy), Object(Magento\\Store\\Model\\StoreManager), Object(Magento\\Framework\\Math\\Ran in /var/app/current/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 116

Regards,
JOINSO

**Comment by joinso** [comment] 2019-11-11 20:18
It does not work:

main.CRITICAL: Notice: Undefined index: XXXXXX in /var/app/current/vendor/magento/module-inventory-source-selection-api/Model/Algorithms/Result/GetDefaultSortedSourcesResult.php on line 126 

Regards,
JOINSO

**Comment by amenk** [comment] 2019-11-12 18:34
@joinso I works for us, what did you do exactly? were all hunks applied?

**Comment by joinso** [comment] 2019-11-28 05:37
Yes, I applied this patch: https://gist.github.com/kassner/3542addaac051acd72f8b7d369052260
But finally i have to do this, to avoid the main.CRITICAL:

            if (isset($itemsTdDeliver[$sourceItem->getSku()]))
            {
              $itemsTdDeliver[$sourceItem->getSku()] -= $qtyToDeduct;  
            }

Regards,
JOINSO

**Comment by smoskaluk** [comment] 2020-02-24 15:29
Closing issue due it not reproducing on mainline MSI branch (1.2-develop)

**Closed as completed by smoskaluk** 2020-02-24 15:29 UTC
Labels: Bug, Progress: good first issue

**Comment by amenk** [comment] 2020-02-26 15:01
@smoskaluk Was this fixed or just not reproduced at all? i.e. was it reproduced in an older branch version and then found to be fixed now? Where can the fixing code be found? With which Magento release will it be fixed?

**Comment by amenk** [comment] 2020-03-09 13:22
@smoskaluk Do you know any commits where this was fixed?

**Comment by DanieliMi** [comment] 2020-03-09 14:31
@amenk it seems to be fixed this commit https://github.com/magento/inventory/commit/89b5f02ef65479d9af22f90f86c98e163f476780
