### ISSUE TITLE
Cannot search stocks in stock grid by keyword.

### ISSUE THREAD

**Issue by nmalevanec** [magento/inventory#1222] opened 2018-05-23 09:02 UTC
### Preconditions
1. Magento with MSI on cloud.

### Steps to reproduce
1. Navigate to admin area.
2. Navigate to Store > Manage Stocks.
3. Create two custom stocks with names "Test Stock 1" and "Test Stock 2" respectively.
4. Enter Test Stock in 'Search by keyword' field and press enter.

### Expected result
1. "Test Stock 1" and "Test Stock 2" should appear in grid.

### Actual result
1. No records appeared in grid.

**Comment by naydav** [comment] 2018-05-23 09:50
Looks like as duplicate of
https://github.com/magento-engcom/msi/issues/325

**Closed as completed** 2018-06-14 11:05 UTC
Labels: Bug, QA Passed
