### ISSUE TITLE
Product grid, filtering and sorting of saleable quantity missing with MSI enabled

### ISSUE THREAD

**Issue by dverkade** [magento/inventory#3250] opened 2020-11-27 09:41 UTC
# Preconditions
1. Magento 2.3.5-p2

### Steps to reproduce
1. Login into the backend and open the product grid
2. Expand the filters, there's no filter for the saleable quantity

### Expected result
1. I'm able to filter on the salable quantity 
2. I'm able to sort on the salable quantity

### Actual result
1. Filtering is missing.
2. Clicking the "Salable quantity" column does not do anything

![image](https://user-images.githubusercontent.com/1058480/100434783-4e80e180-309d-11eb-9a3d-2457d1f416a5.png)

![image](https://user-images.githubusercontent.com/1058480/100434828-5d679400-309d-11eb-80ee-dc1fabdd75b5.png)

**Comment by huykon** [comment] 2021-03-30 14:31
Are there any solution for this issue?

**Comment by DavaGordon** [comment] 2021-03-30 16:30
@magento I am working on this

**Comment by DavaGordon** [comment] 2021-03-31 08:21
@dverkade after reviewing the MSI module in regards to your change i can see that the column has in fact been set to be none filterable / none sortable. this is mainly down to the fact that this columns data is not possible to be sorted due to the possibility of multiple sources of quantity.

**Comment by huykon** [comment] 2021-03-31 08:24
@DavaGordon how can I update salable qty filterable?

**Comment by DavaGordon** [comment] 2021-03-31 08:40
@huykon with the format of the data it is not possible to do so as the data passed to the column is not a string or an integer. setting the columns as filterable/sortable will have no impact.

**Comment by huykon** [comment] 2021-03-31 08:43
Yes I known. This field is not a table column in mysql so we can't make sortable/ filterable. Is that right?

**Comment by DavaGordon** [comment] 2021-03-31 09:01
Yes @huykon the column is a breakdown of multiple quantity sources of inventory based on stock source so the value is a dynamic value based on those values please see screenshot for example

![screencapture-m235-p2-test-admin-catalog-product-index-key-91d5fcf7ff5ff5dea8e299569331e7a1a6145f24fc971effd0dc2264e69a939d-2021-03-31-09_59_48](https://user-images.githubusercontent.com/4630696/113119089-f6ebb180-9207-11eb-831f-395e12d00b8d.png)

**Comment by huykon** [comment] 2021-03-31 09:39
@DavaGordon can we custom filterable work for saleable qty if only 1 source of inventory?

**Comment by DavaGordon** [comment] 2021-03-31 09:44
@huykon not really as it still passes back an the data in the same format. the only way you would be able to do this is by overwriting the UI component to return back a string/int which i dont recommend if you plan on using MSI in the future. if you do not use multi stock sources i would recommend disabling the MSI completely and only relying on the quantity field in magento which does allow filtering and sorting.

**Comment by DavaGordon** [comment] 2021-03-31 10:18
@diazwatson @magento-admin can you please close this ticket as this is not a bug.

**Comment by diazwatson** [comment] 2021-03-31 10:19
Considering this is not an issue, I am closing this issue. Feel free to reopen if you think otherwise.

**Closed as completed by diazwatson** 2021-03-31 10:19 UTC
Labels: Progress: done
