### ISSUE TITLE
Wrong salable quantity

### ISSUE THREAD

**Issue by jorgb90** [magento/inventory#2130] opened 2019-04-02 12:39 UTC
### Preconditions (*)
1. Magento 2.3.1 with MSI

### Steps to reproduce (*)
1. Create a product with two sources. One sources has 1 pc in stock.
2. Create an order and ship this order so its completed.
3. Both sources now say 0 pcs in stock, but salable qty still gives 1.

### Expected result (*)
1. Salable qty to be 0

### Actual result (*)
1. Salable qty is 1

![salableqty](https://user-images.githubusercontent.com/7294081/55402792-9d871400-5554-11e9-8312-5c23ae2732c7.png)

Table inventory_source gives:

![inventorysourcetable](https://user-images.githubusercontent.com/7294081/55402876-cad3c200-5554-11e9-8ed0-946c82b972f1.png)

Table inventory_source_item gives:

![inventorysource](https://user-images.githubusercontent.com/7294081/55402971-fa82ca00-5554-11e9-92e3-ab433985b8ac.png)

**Comment by maghamed** [comment] 2019-04-02 15:35
hey @jorgb90 ,

I don't the the initial reservation created at the time of Order Placement. Just the compensastional one, created at the time of Shipment. 
How did you create the order, which way? REST/SOAP/Front-end/Back-end? 

Do you have any 3rd party extensions which somehow affect Order Placement?

Can you check whether pulgin `\Magento\InventorySales\Plugin\Sales\OrderManagement\AppendReservationsAfterOrderPlacementPlugin` responssible for adding reservation after order placement is called

**Comment by maghamed** [comment] 2019-04-02 16:00
Or, did you change SKU of the product after the order has been placed?

**Comment by jorgb90** [comment] 2019-04-03 07:32
Hi @maghamed,

**How did you create the order, which way? REST/SOAP/Front-end/Back-end?**
Just at the front-end as a normal customer.

**Do you have any 3rd party extensions which somehow affect Order Placement?**
Nope. We only import stock through Xtento stock import plugin, but that has nothing to do with order placement.

**Can you check whether pulgin \Magento\InventorySales\Plugin\Sales\OrderManagement\AppendReservationsAfterOrderPlacementPlugin responssible for adding reservation after order placement is called**
Let me check.

**Or, did you change SKU of the product after the order has been placed?**
No SKU isn't changed. I have more products which are counting wrong.

Is there a way to somehow reindex the salable qty count? Cause this isn't working.

**Edit:** \Magento\InventorySales\Plugin\Sales\OrderManagement\AppendReservationsAfterOrderPlacementPlugin is called. But I maybe have a reason why now, cause we at first disabled Manage stock because of #2113 and we enabled it after the fix. Could that cause this? That the order is placed when Manage stock was disabled and updated with a shipment when Manage stock was enabled?

**Edit 2:**
![skipped](https://user-images.githubusercontent.com/7294081/55463110-9b769100-55f8-11e9-8f2c-b094d411bea3.png)

It is sometimes skipping the order_placed event like you are saying for just random orders..

**Comment by maghamed** [comment] 2019-04-03 10:27
@jorgb90 what exactly you mean saying you disabled stock and then enabled it again? When MSI is enabled we always place reservations at the time of order placement. There is no possibility to avoid that unless you disabled msi modules.
Did you disable MSI modules?

**Comment by maghamed** [comment] 2019-04-03 10:37
Or you initially had another stock assigned to website where you placed that order. Then you assigned stock with ID=2 to that website, while the order has not been completed, and afterward you shipped that order. So that initial reservation and compensational one are created for different stocks which breaks calculation

**Comment by jorgb90** [comment] 2019-04-03 11:15
@maghamed 

**Did you disable MSI modules?**
No just disabled Manage Stock under configuration/catalog/inventory in the back-end.

**Or you initially had another stock assigned to website where you placed that order. So that initial reservation and compensational one are created for different stocks which breaks calculation**
Nope we didn't had another stock assigned. It wouldn't remove the initial order_placed event right? Now they are just not created..

**Edit:**
It could also be that it are just orders which were created before putting MSI live into production.. So the order_placed event never took place, but the shipment_created did. I will monitor if thats the case. If this will persist I will update this ticket. 

If btw this is the case then I think something should be build to prevent the event shipment_created if there isn't a order_placed event? Cause otherwise a lot of people who will enable MSI run into this issue..

**Comment by maghamed** [comment] 2019-04-03 14:38
@jorgb90 , so the issue is that you switched Manage Stock to false for some products. With this configuration setting Magento does not create any reservations at all including both order placement and shipment. When orders were placed you decided to change that configuration setting to true, so that Magento started to handle product quantities. Thus, when you done shipment Magento created compensational transaction , but because the initial transaction has not been created - you have this extra 1 piece of item appear. Since MSI Magento makes Qty calculation at the time of shipment and refund creation, not only order placement as it was before

**Comment by maghamed** [comment] 2019-04-03 14:41
@jorgb90 , so the issue is that you switched Manage Stock to false for some products. With this configuration setting Magento does not create any reservations at all including both order placement and shipment. When orders were placed you decided to change that configuration setting to true, so that Magento started to handle product quantities. Thus, when you done shipment Magento created compensational transaction , but because the initial transaction has not been created - you have this extra 1 piece of item appear. Since MSI Magento make Qty calculation at the time of shipment and refund creation, not only order placement as it was before

**Comment by jorgb90** [comment] 2019-04-03 16:43
@maghamed Its either that (I dont know if the Manage Stock setting disables MSI events?) or it's just that by upgrading Magento and enabling MSI on a production environment (which has already orders placed before MSI was enabled) it creates shipment_created events and thus have a mismatch as it doesn't have a compensational transaction.

**Comment by maghamed** [comment] 2019-04-03 20:55
correct, that's another reason of getting Qty calculation wrong

**Closed as completed** 2019-04-05 05:40 UTC
Labels: Wrong QTY Calculation
