### ISSUE TITLE
Return to Stock checkbox is applied for all products from order not only for selected

### ISSUE THREAD

**Issue by VasylShvorak** [magento/inventory#2851] opened 2020-02-28 12:06 UTC
### Preconditions (*)

1. Magento 2.4-develop with MSI 1.2-develop

### Steps to reproduce (*)

1. Login as customer
2. Add two simple products to cart
3. Place order
4. Create invoice and shipment
5. Check Quantity and Salable Quantity decrease by 1 for appropriate products
![image](https://user-images.githubusercontent.com/26908019/75546726-e7f96500-5a31-11ea-8b2b-767182e44a74.png)
6. Click `Credit Memo` on order page in admin
7. Check `Return to Stock` only for one product
![image](https://user-images.githubusercontent.com/26908019/75546854-3444a500-5a32-11ea-94e9-1fbb834a3118.png)
8. Click `Refund Offline`

### Expected result (*)

1. Only checked product is returned to stock

### Actual result (*)

1. Both products are returned to stock
![image](https://user-images.githubusercontent.com/26908019/75546938-6e15ab80-5a32-11ea-9027-5c4c144f027c.png)

**Comment by smoskaluk** [comment] 2020-03-02 14:40
Hi @VasylShvorak , I tried to reproduce this issue, but got different result - for product which I didn't return to stock the qty on source reduced, but salable qty get wrong

![salable](https://user-images.githubusercontent.com/27818516/75685749-c0113800-5ca3-11ea-935e-ec4047dd9e02.png)

this error caused by wrong extra reservation for this product in table inventory_reservation

![reservation](https://user-images.githubusercontent.com/27818516/75686170-75dc8680-5ca4-11ea-8f22-e72872656bd3.png)

**Comment by smoskaluk** [comment] 2020-03-31 08:37
Fixed by https://github.com/magento/inventory/pull/2896

**Closed as completed by smoskaluk** 2020-03-31 08:37 UTC
Labels: QA Verified, Progress: PR created
