### ISSUE TITLE
Source list is empty on SSA page on order with configurable with custom options

### ISSUE THREAD

**Issue by IvanPletnyov** [magento/inventory#1912] opened 2018-11-16 12:09 UTC
### Preconditions
1. Magento 2 with MSI
2. Create three custom sources
3. Create custom stock with assigned created sources and assigned "main website"
4. Create configurable product with two options (black and white) with assigned custom sources.
5. On configurable product create two custom options

### Steps to reproduce
1. Create order with option black and choice custom options
2. Click "Ship" button

### Expected result
1. On SSA page we can see all assigned sources
2. We can create shipping

### Actual result
1. On SSA page source list is empty
2. After pressing "Source selection Algorithm" button we get never ending preloader
3. We can't create shipping for order

### Additional media
1. Gif
![configurable proof](https://user-images.githubusercontent.com/26973706/48620540-22f49800-e9a9-11e8-8b53-4c22789fa49a.gif)

2. SSA page 
![image](https://user-images.githubusercontent.com/26973706/48620567-49b2ce80-e9a9-11e8-8c5a-c1018caceb1f.png)

3. Order 
![image](https://user-images.githubusercontent.com/26973706/48620580-5800ea80-e9a9-11e8-9e00-6705e96effb7.png)

4. Product grid 
![image](https://user-images.githubusercontent.com/26973706/48620611-6ea74180-e9a9-11e8-84e8-9cdb1791858a.png)

5. Custom options
![image](https://user-images.githubusercontent.com/26973706/48620644-8e3e6a00-e9a9-11e8-8a1c-4ff3a507fb94.png)

**Comment by vickdoan** [comment] 2018-11-21 09:28
@SergeyP18 I think the issue was caused by SKU of child products. It includes the custom option SKU and the system cannot find right item.

File: Magento\InventoryShippingAdminUi\Controller\Adminhtml\SourceSelection\ProcessAlgorithm.php - the execute() function

$requestItems[] = $this->itemRequestFactory->create([
                    'sku' => $data['sku'],
                    'qty' => $data['qty']
                ]);

**Comment by ishakhsuvarov** [comment] 2019-04-16 17:06
Closing, as fix is delivered to `2.3-develop` branch.

Thanks @VitaliyBoyko

**Closed as completed by ishakhsuvarov** 2019-04-16 17:06 UTC
